// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO4JUYW5_FCqb6_kUPgRN1sJfHgXeU6EY',
    appId: '1:539624942834:web:db0b19d9e0c1b2510ef46b',
    messagingSenderId: '539624942834',
    projectId: 'finalproject-flutter-8dd84',
    authDomain: 'finalproject-flutter-8dd84.firebaseapp.com',
    storageBucket: 'finalproject-flutter-8dd84.appspot.com',
    measurementId: 'G-7EK37LK9WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu7uuVrRu2J6iiLDZMVQA_OOMv3CeyH6Q',
    appId: '1:539624942834:android:79d8c7578626199c0ef46b',
    messagingSenderId: '539624942834',
    projectId: 'finalproject-flutter-8dd84',
    storageBucket: 'finalproject-flutter-8dd84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXaC44FnA7RpsQTXOv6-hIoU35T1sPM5g',
    appId: '1:539624942834:ios:e09cf5dc7fcc48ba0ef46b',
    messagingSenderId: '539624942834',
    projectId: 'finalproject-flutter-8dd84',
    storageBucket: 'finalproject-flutter-8dd84.appspot.com',
    androidClientId: '539624942834-9sqjnfbvm12a95eouiep0upn3qpsi6el.apps.googleusercontent.com',
    iosClientId: '539624942834-rhaboqrp0sbofpm3nvnanv5bgpjbb38u.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
